### ISSUE TITLE
Reactivate unit test using TemporaryFolder

### ISSUE THREAD

**Issue by morpheus-87** [dbmdz/digitalcollections-commons#32]
Currently, there's no native TemporaryFolder support in JUnit5, so we disable the following test cases. As soon there's a proper support TemporaryFolder, enable the following test cases.

**Class:** `de.digitalcollections.commons.file.backend.impl.FileResourceRepositoryImplTest`, line 214

**Comment by stefan-it** [comment]
Should be included in upcoming 5.4 version, see [here](https://github.com/junit-pioneer/junit-pioneer/issues/136).

**Comment by morpheus-87** [comment]
And [here](https://github.com/junit-team/junit5/issues/1247#issuecomment-443186276) :)

**Comment by datazuul** [comment]
Implement tests now with org.junit.jupiter.engine.extension.TempDirectory
